---
- name: Homebrew | brew update 1
  homebrew: update_homebrew=yes
  sudo: false

- name: Homebrew | brew tap osx_packages.common.taps
  homebrew_tap: name={{ item }} state=present
  with_items: 
   - "{{ osx_packages.common.taps }}"
  sudo: false

- name: Homebrew | brew update 2
  homebrew: update_homebrew=yes upgrade_all=yes path="{{ executables.brew }}"
  sudo: false

- name: Homebrew | brew install osx_packages.common.packages
  homebrew: name={{ item }} state=present path="{{ executables.brew }}"
  with_items:
   - "{{ osx_packages.common.packages }}"
  sudo: false

- name: Homebrew | Cleanup
  shell: brew cleanup
  sudo: false

- name: Homebrew | brew cask install osx_packages.common.casks
  homebrew_cask: name={{ item }} state=present
  with_items:
   - "{{ osx_packages.common.casks }}"
  sudo: false

- name: Homebrew | Cleanup
  shell: brew cleanup
  sudo: false

- name: Homebrew | Cleanup
  shell: brew cask cleanup
  sudo: false

- name: Homebrew | Ensure casks are linked to /Applications
  shell: brew linkapps --force
  sudo: false
