---
- name: SSH | Create .ssh directory
  file: path=~/.ssh state=directory mode=0740

- name: SSH | Copy config file to .ssh
  copy: src=config dest=~/.ssh/config mode=0600

- name: SSH | Copy private ssh key from NAS server
  copy: src={{ machines.mac_pro.ssh_keys }}/id_rsa dest=~/.ssh/id_rsa mode=0600

- name: SSH | Copy public ssh key from NAS server
  copy: src={{ machines.mac_pro.ssh_keys }}/id_rsa.pub dest=~/.ssh/id_rsa.pub mode=0644
