---
- name: SSH | Create .ssh directory
  file: >
    path=~/.ssh
    state=directory
    mode=0740

- name: SSH | Copy config file to .ssh
  copy: >
    src=config
    dest=~/.ssh/config
    mode=0600

- name: SSH | Copy private ssh key from NAS server
  copy: >
    src={{ machines.mac_pro.ssh_keys.private }}
    dest=~/.ssh/id_rsa
    mode=0600

- name: SSH | Copy public ssh key from NAS server
  copy: >
    src={{ machines.mac_pro.ssh_keys.public }}
    dest=~/.ssh/id_rsa.pub
    mode=0644

- include: authorized_keys.yml
