# file: group_vars/osx.yml
---
system: osx
os: osx

executables:
  brew: /usr/local/bin/brew
  zsh: /usr/local/bin/zsh

directories:
  etc: /usr/local/etc
  var: /usr/local/var

files:
  github_rate_limit_token: /Volumes/Poseidon/Backup-Recovery-Provision/Dev Configs/github-rate-limit-token

admin:
  user:
    name: admin
    group: staff
    shell: "{{ executables.zsh }}"

  template_home: home/admin
  home: /Users/admin
  system: osx
  ruby:
    version: "{{ ruby.version }}"
  rbenv:
    global: "{{ ruby.version }}"

machines:
  mac_pro:
    ssh_keys: /Volumes/Poseidon/Backup-Recovery-Provision/Machines/MacPro/SSH-Keys
  rmbp:
    ssh_keys: /Volumes/Poseidon/Backup-Recovery-Provision/Machines/rMbp/SSH-Keys
  BP-Desktop:
    ssh_keys: /Volumes/Poseidon/Backup-Recovery-Provision/Machines/BP-Desktop/SSH-Keys
  HP-Pavillion:
    ssh_keys: /Volumes/Poseidon/Backup-Recovery-Provision/Machines/HP-Pavillion/SSH-Keys
  NAS-Synology-1:
    ssh_keys: /Volumes/Poseidon/Backup-Recovery-Provision/Machines/NAS-Synology-1/SSH-Keys
  NAS-Synology-2:
    ssh_keys: /Volumes/Poseidon/Backup-Recovery-Provision/Machines/NAS-Synology-2/SSH-Keys
