---
- name: Sys Config | System
  shell: "{{ item }}"
  with_items: 
   - "{{ osx_config_sys.system }}"

- name: Sys Config | System
  shell: "{{ item }}"
  with_items: 
   - "{{ osx_config_sys.system_ssd_tweaks }}"
