- hosts: all
  sudo: false
  roles:
   - { role: git }
   - { role: ssh }
   - { role: ohmyzsh }
   - { role: configsys }
   - { role: homebrew }
   - { role: configapp }
   - { role: nodejs }
   - { role: bower }
